/**
 * System card page
 *
 * CONTENT EDITING:
 *   - English: public/content/system-card-en.md
 *   - French:  public/content/fiche-systeme-fr.md
 *
 * The whole document is rendered. Keep the "On this page" links in the
 * markdown in step with the h2 headings: heading ids are generated by
 * headingId() below, using the same rules as GitHub anchors.
 * Frontmatter supplies the page title and meta description.
 */

import React, { useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { GcdsContainer, GcdsText, GcdsLink } from '@gcds-core/components-react';
import { useTranslations } from '../hooks/useTranslations.js';
import { useMarkdownWithFrontmatter } from '../hooks/useMarkdownWithFrontmatter.js';
import { useFocusOnChange } from '../hooks/useFocusOnChange.js';
import { getPath } from '../utils/routes.js';
import StatusMessage from '../components/admin/StatusMessage.js';

const textOf = (children) =>
  React.Children.toArray(children)
    .map((c) => (typeof c === 'string' ? c : c?.props?.children ? textOf(c.props.children) : ''))
    .join('');

// Same rules as GitHub heading anchors: lowercase, drop punctuation, spaces to hyphens.
export const headingId = (children) =>
  textOf(children)
    .toLowerCase()
    .trim()
    .replace(/[^\p{L}\p{N}\s-]/gu, '')
    .replace(/\s/g, '-');

const SystemCardPage = ({ lang = 'en' }) => {
  const { t } = useTranslations(lang);
  const filename = lang === 'fr' ? 'fiche-systeme-fr.md' : 'system-card-en.md';
  const { frontmatter, content, loading, error } = useMarkdownWithFrontmatter(filename);
  const errorRef = useFocusOnChange(error);

  useEffect(() => {
    if (!loading && frontmatter.title) {
      document.title = frontmatter.title;
      const descMeta = document.querySelector('meta[name="description"]');
      if (descMeta && frontmatter.description) {
        descMeta.setAttribute('content', frontmatter.description);
      }
    }
  }, [frontmatter, loading]);

  const backToAbout = (
    <nav className="mb-400" aria-label={t('systemCardPage.title')}>
      <GcdsText>
        <GcdsLink href={getPath('about', lang)}>{t('systemCardPage.backToAbout')}</GcdsLink>
      </GcdsText>
    </nav>
  );

  if (loading) {
    return (
      <GcdsContainer layout="page" className="mb-600">
        <StatusMessage loading message={t('common.loading')} />
      </GcdsContainer>
    );
  }

  if (error) {
    return (
      <GcdsContainer layout="page" className="mb-600">
        <h1 className="mb-400">{t('systemCardPage.title')}</h1>
        {backToAbout}
        <StatusMessage
          variant="error"
          message={t('aboutPage.loadError')}
          ref={errorRef}
          tabIndex={-1}
          announce={false}
          announcedVia="focus"
          className="focus-target"
        />
      </GcdsContainer>
    );
  }

  return (
    <GcdsContainer layout="page" className="mb-600">
      <div className="how-to-content">
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            h1: ({ children }) => (
              <>
                <h1 className="mb-400">{children}</h1>
                {backToAbout}
              </>
            ),
            h2: ({ children }) => (
              <h2 id={headingId(children)} className="mt-400 mb-300">{children}</h2>
            ),
            h3: ({ children }) => (
              <h3 id={headingId(children)} className="mt-400 mb-300">{children}</h3>
            ),
            p: ({ children }) => <p className="mb-300">{children}</p>,
            // GCDS resets list markers and width; see HowToPage.js.
            ul: ({ children }) => (
              <ul className="list-disc mb-400 text-measure canada-ca-list-spcd-2">{children}</ul>
            ),
            ol: ({ children }) => (
              <ol className="list-decimal mb-400 text-measure canada-ca-list-spcd-2">{children}</ol>
            ),
            a: ({ href, children }) => {
              const isExternal = /^https?:\/\//.test(href || '');
              const isPdf = /\.pdf$/i.test(href || '');
              return isExternal || isPdf ? (
                <GcdsLink href={href} target="_blank" lang={lang}>
                  {children}
                </GcdsLink>
              ) : (
                <a href={href}>{children}</a>
              );
            },
            img: ({ src, alt }) => <img src={src} alt={alt} className="how-to-screenshot" />,
            table: ({ children }) => (
              <div className="how-to-table-scroll" tabIndex={0}>
                <table>{children}</table>
              </div>
            ),
          }}
        >
          {content}
        </ReactMarkdown>
      </div>
    </GcdsContainer>
  );
};

export default SystemCardPage;
