name: Deploy to App Runner (Repo mode)
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via AWS CLI (Repository mode)
        run: |
          aws apprunner update-service \
            --cli-input-yaml file://apprunner-update.yaml \
            --region ${{ secrets.AWS_REGION }}


      - name: Wait for service running
        run: |
          aws apprunner wait service-running \
            --service-arn "${{ secrets.APP_RUNNER_SERVICE_ARN }}" \
            --region ${{ secrets.AWS_REGION }}

      - name: Retrieve service URL
        id: svc
        run: |
          echo "service-url=$(aws apprunner describe-service \
            --service-arn "${{ secrets.APP_RUNNER_SERVICE_ARN }}" \
            --query 'Service.ServiceUrl' \
            --output text \
            --region ${{ secrets.AWS_REGION }})" >> $GITHUB_ENV

      - name: Deployment complete
        run: echo "✅ App Runner URL: ${{ env.service-url }}"
