name: Deploy to App Runner (Repository mode)
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy using AWS CLI (repository mode)
        run: |
          aws apprunner update-service \
            --service-arn "${{ secrets.APP_RUNNER_SERVICE_ARN }}" \
            --source-configuration "CodeRepository={ConfigurationSource=REPOSITORY}" \
            --region ${{ secrets.AWS_REGION }}

      - name: Wait for service to stabilize
        run: |
          aws apprunner wait service-running \
            --service-arn "${{ secrets.APP_RUNNER_SERVICE_ARN }}" \
            --region ${{ secrets.AWS_REGION }}

      - name: Get App Runner URL
        id: get-url
        run: |
          URL=$(aws apprunner describe-service \
            --service-arn "${{ secrets.APP_RUNNER_SERVICE_ARN }}" \
            --query 'Service.ServiceUrl' \
            --output text \
            --region ${{ secrets.AWS_REGION }})
          echo "service-url=$URL" >> $GITHUB_ENV

      - name: 🎉 Deployment complete
        run: echo "✅ App Runner URL is ${{ env.service-url }}"
