name: Deploy to App Runner (Repo mode)

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Switch to Repository mode
        run: |
          aws apprunner update-service \
            --service-arn "${{ secrets.APP_RUNNER_SERVICE_ARN }}" \
            --source-configuration "{
              \"CodeRepository\": {
                \"RepositoryUrl\": \"https://github.com/${{ github.repository }}\",
                \"SourceCodeVersion\": {\"Type\":\"BRANCH\",\"Value\":\"main\"},
                \"CodeConfiguration\": {\"ConfigurationSource\":\"REPOSITORY\"}
              }
            }" \
            --region ${{ secrets.AWS_REGION }}

      - name: Wait for App Runner service to be RUNNING
        run: |
          echo "Waiting for App Runner service to reach RUNNING status..."
          for i in {1..30}; do
            STATUS=$(aws apprunner describe-service \
              --service-arn "${{ secrets.APP_RUNNER_SERVICE_ARN }}" \
              --region ${{ secrets.AWS_REGION }} \
              --query 'Service.Status' \
              --output text)
            echo "Status: $STATUS"
            if [ "$STATUS" == "RUNNING" ]; then
              echo "✅ App Runner service is RUNNING."
              break
            elif [ "$STATUS" == "FAILED" ]; then
              echo "❌ App Runner service failed to start."
              exit 1
            fi
            sleep 10
          done

      - name: Get App Runner URL
        id: get-url
        run: |
          URL=$(aws apprunner describe-service \
            --service-arn "${{ secrets.APP_RUNNER_SERVICE_ARN }}" \
            --query 'Service.ServiceUrl' \
            --output text \
            --region ${{ secrets.AWS_REGION }})
          echo "service-url=$URL" >> $GITHUB_ENV

      - name: Deployment complete
        run: echo "✅ App Runner URL ${{ env.service-url }}"
