name: "Terraform apply staging"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - "!terragrunt/env/production/**"
      - ".github/workflows/tf_apply_staging.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.10.4
  TERRAGRUNT_VERSION: 0.72.3
  TF_VAR_docdb_username: ${{ secrets.DOCDB_USERNAME}}
  TF_VAR_docdb_password: ${{ secrets.DOCDB_PASSWORD}}
  TF_VAR_azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY}}
  TF_VAR_azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT}}
  TF_VAR_azure_openai_api_version: ${{ secrets.AZURE_OPENAI_API_VERSION}}
  TF_VAR_canada_ca_search_uri: ${{ secrets.CANADA_CA_SEARCH_URI}}
  TF_VAR_canada_ca_search_api_key: ${{ secrets.CANADA_CA_SEARCH_API_KEY}}
  TF_VAR_user_agent: ${{ secrets.USER_AGENT}}
  TF_VAR_jwt_secret_key: ${{ secrets.JWT_SECRET_KEY}}
  TF_VAR_sentinel_customer_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
  TF_VAR_sentinel_shared_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
  TF_VAR_google_api_key: ${{ secrets.GOOGLE_API_KEY}}
  TF_VAR_google_search_engine_id: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID}}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terragrunt-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform Tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::992382783569:role/ai-answers-apply
          role-session-name: TFApply
          aws-region: ${{ env.AWS_REGION }}

      - name: Apply ssm
        working-directory: terragrunt/env/staging/ssm
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply hosted zone
        working-directory: terragrunt/env/staging/hosted_zone
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply network
        working-directory: terragrunt/env/staging/network
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply ecr
        working-directory: terragrunt/env/staging/ecr
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply database
        working-directory: terragrunt/env/staging/database
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply iam
        working-directory: terragrunt/env/staging/iam
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply load balancer
        working-directory: terragrunt/env/staging/load_balancer
        run: terragrunt apply --terragrunt-non-interactive -auto-approve

      - name: Apply ecs
        working-directory: terragrunt/env/staging/ecs
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
