name: "Terraform plan staging"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terragrunt/**"
      - "!terragrunt/env/production/**"
      - ".github/workflows/tf_plan_staging.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.11.2
  TERRAGRUNT_VERSION: 0.75.6
  TF_VAR_docdb_username: ${{ secrets.DOCDB_USERNAME}}
  TF_VAR_docdb_password: ${{ secrets.DOCDB_PASSWORD}}
  TF_VAR_azure_openai_api_key: ${{ secrets.AZURE_OPENAI_API_KEY}}
  TF_VAR_azure_openai_endpoint: ${{ secrets.AZURE_OPENAI_ENDPOINT}}
  TF_VAR_azure_openai_api_version: ${{ secrets.AZURE_OPENAI_API_VERSION}}
  TF_VAR_canada_ca_search_uri: ${{ secrets.CANADA_CA_SEARCH_URI}}
  TF_VAR_canada_ca_search_api_key: ${{ secrets.CANADA_CA_SEARCH_API_KEY}}
  TF_VAR_user_agent: ${{ secrets.USER_AGENT}}
  TF_VAR_jwt_secret_key: ${{ secrets.JWT_SECRET_KEY}}
  TF_VAR_sentinel_customer_id: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
  TF_VAR_sentinel_shared_key: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
  TF_VAR_google_api_key: ${{ secrets.GOOGLE_API_KEY}}
  TF_VAR_google_search_engine_id: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID}}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terraform-plan:
    if: github.repository == 'cds-snc/ai-answers'
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: ecr
          - module: ssm
          - module: network
          - module: hosted_zone
          - module: load_balancer
          - module: database
          - module: iam
          - module: ecs
          - module: pr_review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform Tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::992382783569:role/ai-answers-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform plan
        uses: cds-snc/terraform-plan@7d4ab0010e76b09dfc1d8a343d2c7ddaa2b4df4f # v3.3.2
        with:
          comment-delete: true
          comment-title: "Staging: ${{ matrix.module }}"
          directory: ./terragrunt/env/staging/${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
