name: "Terraform plan staging"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terragrunt/**"
      - "!terragrunt/env/staging/**"
      - ".github/workflows/tf_plan_staging.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.10.4
  TERRAGRUNT_VERSION: 0.72.3
  TF_VAR_docdb_username: ${{ secrets.DOCDB_USERNAME}}
  TF_VAR_docdb_password: ${{ secrets.DOCDB_PASSWORD}}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terraform-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: ecr
          - module: ssm
          - module: network
          - module: hosted_zone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform Tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::730335533085:role/ai-answers-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform plan
        uses: cds-snc/terraform-plan@v3.2.2
        with:
          comment-delete: true
          comment-title: "Staging: ${{ matrix.module }}"
          directory: ./terragrunt/env/staging/${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
